apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pfzwr2rpa-go 
  janus-idp.io/tekton: pfzwr2rpa-go
  backstage.io/kubernetes-id: pfzwr2rpa-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pfzwr2rpa-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml